[env]
PLAYWRIGHT_BROWSERS_PATH = "0"

[phases.setup]
aptPkgs = [
  "libglib2.0-0",
  "libnss3",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libdrm2",
  "libxkbcommon0",
  "libxcomposite1",
  "libxdamage1",
  "libxfixes3",
  "libxrandr2",
  "libasound2",
  "libxshmfence1",
  "libgbm1",
  "libpangocairo-1.0-0",
  "libpango-1.0-0",
  "libcairo2",
  "libcups2",
  "libgtk-3-0",
  "libx11-6",
  "libx11-xcb1",
  "libxcb1",
  "libxext6",
  "libxrender1",
  "fonts-liberation",
  "libdbus-1-3"
]
cmds = ["python3 -m playwright install chromium"]
